name: Simple Sync from Er_classcode
on:
  workflow_dispatch:  # Manual trigger only for testing
  schedule:
    - cron: '0 2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync files
        run: |
          # Clone source repo to temp directory
          git clone https://github.com/agenticgogol/Er_classcode.git temp_source
          
          # Copy all files except .git
          rsync -av --exclude='.git' temp_source/ ./
          
          # Clean up
          rm -rf temp_source
          
          # Check if there are changes
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Sync from Er_classcode $(date)"
            git push
            echo "Changes synced successfully"
          else
            echo "No changes to sync"
          fi
