name: Sync from Er_classcode
on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  push:
    branches: [ main ]  # Also sync when main branch is updated

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch full history
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Add source repo as remote
        run: |
          git remote add source https://github.com/agenticgogol/Er_classcode.git || true
          git fetch source
      
      - name: Sync changes
        run: |
          # Create or switch to sync branch
          git checkout -B sync-from-source
          
          # Merge source changes
          git merge source/main --allow-unrelated-histories -X theirs
          
          # Push sync branch
          git push origin sync-from-source --force
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-from-source
          base: main
          title: 'Auto-sync from Er_classcode'
          body: |
            This PR automatically syncs changes from the source repository.
            
            **Source:** https://github.com/agenticgogol/Er_classcode.git
            **Destination:** https://github.com/mdansari1204/llm-agentic-exploration.git
            
            Please review the changes before merging.
          draft: false
          delete-branch: true
